=== FrontierScience/asi_interpreter/src/java/org/fstrf/stanfordAsiInterpreter/resistance/ASI2.2.dtd
<!-- 
This DTD is being put together to indicate the format the various
drug resistance algorithms should use.

version 2.2  added RESULT_COMMENTS and children
by kyle lambert
-->


<!ELEMENT ALGORITHM (ALGNAME, ALGVERSION?, ALGDATE?, DEFINITIONS, DRUG*, MUTATION_COMMENTS?,RESULT_COMMENTS?)>

<!-- *************************************************************** -->
<!ELEMENT ALGNAME (#PCDATA)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT ALGVERSION (#PCDATA)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT ALGDATE (#PCDATA)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT DEFINITIONS (GENE_DEFINITION*, LEVEL_DEFINITION*, DRUGCLASS*, GLOBALRANGE?,
                       COMMENT_DEFINITIONS?)>
<!ELEMENT GENE_DEFINITION (NAME, DRUGCLASSLIST?)>
<!ELEMENT DRUGCLASSLIST (#PCDATA)>                    
<!ELEMENT LEVEL_DEFINITION (ORDER, ORIGINAL, SIR)>
<!ELEMENT ORDER (#PCDATA)>
<!ELEMENT ORIGINAL (#PCDATA)>
<!ELEMENT SIR (#PCDATA)>
<!ELEMENT DRUGCLASS (NAME, DRUGLIST)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT DRUGLIST (#PCDATA)>
<!ELEMENT GLOBALRANGE (#PCDATA)>
<!ELEMENT COMMENT_DEFINITIONS (COMMENT_STRING+)>
<!ELEMENT COMMENT_STRING (TEXT, SORT_TAG?)>
<!ATTLIST COMMENT_STRING   id ID #REQUIRED>     
<!-- the html version of the HIVdb program expects the COMMENT_STRING id to be <geneName>_<mutation>_<commentType>
     the commentType is used for grouping the comments (uppercased) and should match the name of the appropriate MutationClassification element in the virus definition -->
<!ELEMENT TEXT (#PCDATA)>
<!ELEMENT SORT_TAG (#PCDATA)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT DRUG (NAME, FULLNAME?, RULE*)>
<!ELEMENT FULLNAME (#PCDATA)>
<!ELEMENT RULE (CONDITION, ACTIONS)>
<!ELEMENT CONDITION (#PCDATA)>
<!ELEMENT ACTIONS (LEVEL?, SCORERANGE?, COMMENT?)>
<!ELEMENT LEVEL (#PCDATA)>
<!ELEMENT SCORERANGE (#PCDATA | USE_GLOBALRANGE)*>
<!ELEMENT USE_GLOBALRANGE EMPTY>
<!ELEMENT COMMENT EMPTY>
<!ATTLIST COMMENT   ref IDREF #REQUIRED>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT MUTATION_COMMENTS (GENE*)>
<!ELEMENT GENE (NAME, RULE+)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT RESULT_COMMENTS (RESULT_COMMENT_RULE*)>
<!ELEMENT RESULT_COMMENT_RULE (DRUG_LEVEL_CONDITIONS,LEVEL_ACTION)>
<!ELEMENT DRUG_LEVEL_CONDITIONS (DRUG_LEVEL_CONDITION+)>
<!ELEMENT DRUG_LEVEL_CONDITION (DRUG_NAME,(LTE | LT | GTE | GT | EQ | NEQ)+)>
<!ELEMENT DRUG_NAME (#PCDATA)>
<!ELEMENT LEVEL_ACTION (COMMENT)>
<!---Comparison operators for the LEVEL_CONDITION element --> 
<!ELEMENT LTE (#PCDATA)>
<!ELEMENT LT (#PCDATA)>
<!ELEMENT GTE (#PCDATA)>
<!ELEMENT GT (#PCDATA)>
<!ELEMENT EQ (#PCDATA)>
<!ELEMENT NEQ (#PCDATA)>
<!-- *************************************************************** -->

=== FrontierScience/asi_interpreter/test/files/result_based_comments/ComparisonTest.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ALGORITHM SYSTEM "http://sierra2.stanford.edu/sierra/ASI2.2.dtd">
<ALGORITHM>
  <ALGNAME>KPL</ALGNAME>
  <ALGVERSION>1.1</ALGVERSION>
  <ALGDATE>2019-08-16</ALGDATE>
  <DEFINITIONS>
    <GENE_DEFINITION>
      <NAME>PR</NAME>
      <DRUGCLASSLIST>PI</DRUGCLASSLIST>
    </GENE_DEFINITION>
    
    <LEVEL_DEFINITION>
      <ORDER>1</ORDER>
      <ORIGINAL>Susceptible</ORIGINAL>
      <SIR>S</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>2</ORDER>
      <ORIGINAL>Potential Low-Level Resistance</ORIGINAL>
      <SIR>S</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>3</ORDER>
      <ORIGINAL>Low-Level Resistance</ORIGINAL>
      <SIR>I</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>4</ORDER>
      <ORIGINAL>Intermediate Resistance</ORIGINAL>
      <SIR>I</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>5</ORDER>
      <ORIGINAL>High-Level Resistance</ORIGINAL>
      <SIR>R</SIR>
    </LEVEL_DEFINITION>
    
    <DRUGCLASS>
      <NAME>PI</NAME>
      <DRUGLIST>ATV/r</DRUGLIST>
    </DRUGCLASS>
    
    <GLOBALRANGE><![CDATA[(-INF TO 9 => 1,  10 TO 14 => 2,  15 TO 29 => 3,  30 TO 59 => 4,  60 TO INF => 5)]]></GLOBALRANGE>
    
    <COMMENT_DEFINITIONS>
      
      <COMMENT_STRING id="GTE2">
      	<TEXT><![CDATA[Level is greater than or equal to 2]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="GTE3">
      	<TEXT><![CDATA[Level is greater than or equal to 3]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="GTE4">
      	<TEXT><![CDATA[Level is greater than or equal to 4]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  
	  <COMMENT_STRING id="GT2">
      	<TEXT><![CDATA[Level is greater than 2]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="GT3">
      	<TEXT><![CDATA[Level is greater than 3]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="GT4">
      	<TEXT><![CDATA[Level is greater than 4]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  
	  <COMMENT_STRING id="LTE2">
      	<TEXT><![CDATA[Level is less than or equal to 2]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="LTE3">
      	<TEXT><![CDATA[Level is less than or equal to 3]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="LTE4">
      	<TEXT><![CDATA[Level is less than or equal to 4]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  
	  <COMMENT_STRING id="LT2">
      	<TEXT><![CDATA[Level is less than 2]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="LT3">
      	<TEXT><![CDATA[Level is less than 3]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="LT4">
      	<TEXT><![CDATA[Level is less than 4]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  
	  <COMMENT_STRING id="EQ2">
      	<TEXT><![CDATA[Level is equal to 2]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="EQ3">
      	<TEXT><![CDATA[Level is equal to 3]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="EQ4">
      	<TEXT><![CDATA[Level is equal to 4]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  
	  <COMMENT_STRING id="NEQ2">
      	<TEXT><![CDATA[Level is not equal to 2]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="NEQ3">
      	<TEXT><![CDATA[Level is not equal to 3]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="NEQ4">
      	<TEXT><![CDATA[Level is not equal to 4]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
    </COMMENT_DEFINITIONS>
    
  </DEFINITIONS>
  
 
	<DRUG>
        <NAME>ATV/r</NAME>
        <FULLNAME>atazanavir/r</FULLNAME>
        <RULE>
            <CONDITION>
                SCORE FROM (20T => 25)
            </CONDITION>
            <ACTIONS>
                <SCORERANGE><USE_GLOBALRANGE/></SCORERANGE>
            </ACTIONS>
        </RULE>
    </DRUG>

  <RESULT_COMMENTS>
  
  <!--KPL Note 16-Aug-2019: The DRUG_LEVEL_CONDITIONS examples here are messy because I had to reformat this document
  after the ASI 1.4.0 to 1.5.0 syntax change. Check the KPL_1.1.xml doc for a cleaner example of how to format this section -->
		
		<!--GTE-->
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<GTE>2</GTE>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="GTE2"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<GTE>3</GTE>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="GTE3"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<GTE>4</GTE>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="GTE4"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		
		<!--GT-->
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<GT>2</GT>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="GT2"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<GT>3</GT>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="GT3"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<GT>4</GT>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="GT4"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		
		<!--LTE-->
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<LTE>2</LTE>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="LTE2"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<LTE>3</LTE>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="LTE3"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<LTE>4</LTE>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="LTE4"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		
		<!--LT-->
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<LT>2</LT>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="LT2"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<LT>3</LT>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="LT3"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<LT>4</LT>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="LT4"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		
		<!--EQ-->
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<EQ>2</EQ>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="EQ2"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<EQ>3</EQ>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="EQ3"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<EQ>4</EQ>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="EQ4"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		
		<!--NEQ-->
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<NEQ>2</NEQ>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="NEQ2"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<NEQ>3</NEQ>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="NEQ3"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
		<RESULT_COMMENT_RULE>
			<DRUG_LEVEL_CONDITIONS><DRUG_LEVEL_CONDITION>
				<DRUG_NAME>ATV/r</DRUG_NAME>
				<NEQ>4</NEQ>
			</DRUG_LEVEL_CONDITION></DRUG_LEVEL_CONDITIONS>
			<LEVEL_ACTION>
				<COMMENT ref="NEQ4"/>
			</LEVEL_ACTION>
		</RESULT_COMMENT_RULE>
  </RESULT_COMMENTS>
</ALGORITHM>

=== FrontierScience/asi_interpreter/test/files/result_based_comments/LevelRuleWithNoCondition.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ALGORITHM SYSTEM "http://sierra2.stanford.edu/sierra/ASI2.2.dtd">
<ALGORITHM>
  <ALGNAME>KPL</ALGNAME>
  <ALGVERSION>1.0</ALGVERSION>
  <ALGDATE>2018-11-20</ALGDATE>
  <DEFINITIONS>
    <GENE_DEFINITION>
      <NAME>PR</NAME>
      <DRUGCLASSLIST>PI</DRUGCLASSLIST>
    </GENE_DEFINITION>
    
    <LEVEL_DEFINITION>
      <ORDER>1</ORDER>
      <ORIGINAL>Susceptible</ORIGINAL>
      <SIR>S</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>2</ORDER>
      <ORIGINAL>Potential Low-Level Resistance</ORIGINAL>
      <SIR>S</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>3</ORDER>
      <ORIGINAL>Low-Level Resistance</ORIGINAL>
      <SIR>I</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>4</ORDER>
      <ORIGINAL>Intermediate Resistance</ORIGINAL>
      <SIR>I</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>5</ORDER>
      <ORIGINAL>High-Level Resistance</ORIGINAL>
      <SIR>R</SIR>
    </LEVEL_DEFINITION>
    
    <DRUGCLASS>
      <NAME>PI</NAME>
      <DRUGLIST>IDV/r</DRUGLIST>
    </DRUGCLASS>
    
    <GLOBALRANGE><![CDATA[(-INF TO 9 => 1,  10 TO 14 => 2,  15 TO 29 => 3,  30 TO 59 => 4,  60 TO INF => 5)]]></GLOBALRANGE>
    
    <COMMENT_DEFINITIONS>
      <COMMENT_STRING id="PR82L">
      	<TEXT><![CDATA[Wow that's a pretty rad mutation. Love it.]]></TEXT>
      	<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="LowLevelWarning">
      	<TEXT><![CDATA[Result was low level -- probably fine]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="HighLevelWarning">
		<TEXT><![CDATA[Result was high level -- better check that out]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
	  </COMMENT_STRING>
    </COMMENT_DEFINITIONS>
    
  </DEFINITIONS>
  
  <DRUG>
    <NAME>IDV/r</NAME>
    <FULLNAME>indinavir/r</FULLNAME>
    <RULE>
      <CONDITION><![CDATA[SCORE FROM(10F => 10,
                         20T => 5,
                         MAX ( 24F => 5, 24I => 15, 24M => 5 ),
                         MAX ( 82A => 30, 82C => 15, 82F => 30, 82L => 10, 82M => 30, 82S => 30, 82T => 30 ),
                         (11IL AND 32I) => 5)]]></CONDITION>
      <ACTIONS>
        <SCORERANGE>
          <USE_GLOBALRANGE/>
        </SCORERANGE>
      </ACTIONS>
    </RULE>
  </DRUG>
  
  <MUTATION_COMMENTS>
    <GENE>
      <NAME>PR</NAME>
      <RULE>
        <CONDITION>82L</CONDITION>
        <ACTIONS>
          <COMMENT ref="PR82L"/>
        </ACTIONS>
      </RULE>
    </GENE>
  </MUTATION_COMMENTS>
  
  <RESULT_COMMENTS>
  	<RESULT_COMMENT_DRUG>
  		<NAME>IDV/r</NAME>
		<LEVEL_RULE>
			
		</LEVEL_RULE>
		<LEVEL_RULE>
			<LEVEL_CONDITION>
				<GT>4</GT>
			</LEVEL_CONDITION>
			<LEVEL_ACTION>
				<COMMENT ref="HighLevelWarning"/>
			</LEVEL_ACTION>
		</LEVEL_RULE>
  	</RESULT_COMMENT_DRUG>
  </RESULT_COMMENTS>
</ALGORITHM>

=== FrontierScience/asi_interpreter/test/files/result_based_comments/EmptyLevelAction.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ALGORITHM SYSTEM "http://sierra2.stanford.edu/sierra/ASI2.2.dtd">
<ALGORITHM>
  <ALGNAME>KPL</ALGNAME>
  <ALGVERSION>1.1</ALGVERSION>
  <ALGDATE>2019-08-15</ALGDATE>
  <DEFINITIONS>
    <GENE_DEFINITION>
      <NAME>PR</NAME>
      <DRUGCLASSLIST>PI</DRUGCLASSLIST>
    </GENE_DEFINITION>
    
    <LEVEL_DEFINITION>
      <ORDER>1</ORDER>
      <ORIGINAL>Susceptible</ORIGINAL>
      <SIR>S</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>2</ORDER>
      <ORIGINAL>Potential Low-Level Resistance</ORIGINAL>
      <SIR>S</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>3</ORDER>
      <ORIGINAL>Low-Level Resistance</ORIGINAL>
      <SIR>I</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>4</ORDER>
      <ORIGINAL>Intermediate Resistance</ORIGINAL>
      <SIR>I</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>5</ORDER>
      <ORIGINAL>High-Level Resistance</ORIGINAL>
      <SIR>R</SIR>
    </LEVEL_DEFINITION>
    
    <DRUGCLASS>
      <NAME>PI</NAME>
      <DRUGLIST>IDV/r, ATV/r, LPV/r</DRUGLIST>
    </DRUGCLASS>
    
    <GLOBALRANGE><![CDATA[(-INF TO 9 => 1,  10 TO 14 => 2,  15 TO 29 => 3,  30 TO 59 => 4,  60 TO INF => 5)]]></GLOBALRANGE>
    
    <COMMENT_DEFINITIONS>
      <COMMENT_STRING id="PR82L">
      	<TEXT><![CDATA[Wow that's a pretty rad mutation. Love it.]]></TEXT>
      	<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="LowLevelWarning">
      	<TEXT><![CDATA[Result was low level -- probably fine]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
	  <COMMENT_STRING id="HighLevelWarning">
		<TEXT><![CDATA[Result was high level -- better check that out]]></TEXT>
		<SORT_TAG>1</SORT_TAG>
	  </COMMENT_STRING>
    </COMMENT_DEFINITIONS>
    
  </DEFINITIONS>
  
  <DRUG>
    <NAME>IDV/r</NAME>
    <FULLNAME>indinavir/r</FULLNAME>
    <RULE>
      <CONDITION><![CDATA[SCORE FROM(10F => 10,
                         20T => 5,
                         MAX ( 24F => 5, 24I => 15, 24M => 5 ),
                         MAX ( 82A => 30, 82C => 15, 82F => 30, 82L => 15, 82M => 30, 82S => 30, 82T => 30 ),
                         (11IL AND 32I) => 5)]]></CONDITION>
      <ACTIONS>
        <SCORERANGE>
          <USE_GLOBALRANGE/>
        </SCORERANGE>
      </ACTIONS>
    </RULE>
  </DRUG>
  
  <DRUG>
        <NAME>LPV/r</NAME>
        <FULLNAME>lopinavir/r</FULLNAME>
        <RULE>
            <CONDITION>
                SCORE FROM (10F => 5,
                            MAX ( 24I => 10, 24FM => 5 ),
                            32I => 15,
                            33F => 5,
                            MAX ( 46IL => 10, 46V => 5 ),
                            MAX ( 47A => 60, 47V => 15 ),
                            48ALMQSTV => 10,
                            MAX ( 50V => 30, 50L AND EXCLUDE 50(NOT L) => -10 ),
                            MAX ( 54LMV => 15, 54AST => 10 ),
                            73ACSTV => 5,
                            74P => 5,
                            76V => 30,
                            MAX ( 82AF => 30, 82MST => 25, 82CL => 10 ),
                            MAX ( 84A => 60, 84CV => 30 ),
                            90M => 15,
                            (32I AND 47V) => 10,
                            (32I AND 54ML) => 10,
                            (46IL AND 76V) => 10,
                            (46ILV AND 82AFSTMC) => 5,
                            (47V AND 54ML) => 10,
                            (54VSTAML AND 82AFSTMC) => 10,
                            (82AFSTMC AND 24IFM) => 10,
                            (90M AND 82AFSTMC) => 5,
                            (90M AND 84V) => 5
                           )
            </CONDITION>
            <ACTIONS>
                <SCORERANGE><USE_GLOBALRANGE/></SCORERANGE>
            </ACTIONS>
        </RULE>
    </DRUG>
    
    <DRUG>
        <NAME>ATV/r</NAME>
        <FULLNAME>atazanavir/r</FULLNAME>
        <RULE>
            <CONDITION>
                SCORE FROM (20T => 5,
                            MAX ( 24I => 10, 24FM => 5 ),
                            32I => 15,
                            33F => 5,
                            46ILV => 10,
                            47AV => 5,
                            MAX ( 48MV => 30, 48ALQST => 10 ),
                            50L => 60,
                            53L => 10,
                            54ALMSTV => 15,
                            58E => 5,
                            71IL => 5,
                            MAX ( 73ACST => 10, 73V => 5 ),
                            74P => 10,
                            76V AND EXCLUDE 76(NOT V) => -5,
                            MAX ( 82ST => 25, 82AF => 15, 82CLM => 60 ),
                            83D => 10,
                            84ACV => 60,
                            MAX ( 88S => 60, 88GT => 15, 88D => 5 ),
                            90M => 25,
                            (46ILV AND 82ATSFMCL) => 10,
                            (46ILV AND 90M) => 10,
                            (53L AND 90M) => 10,
                            (54AVSTLM AND 82ATSFMCL) => 10,
                            (73STCA AND 90M) => 10,
                            (82ATSFMCL AND 90M) => 10
                           )
            </CONDITION>
            <ACTIONS>
                <SCORERANGE><USE_GLOBALRANGE/></SCORERANGE>
            </ACTIONS>
        </RULE>
    </DRUG>
  
  <MUTATION_COMMENTS>
    <GENE>
      <NAME>PR</NAME>
      <RULE>
        <CONDITION>82L</CONDITION>
        <ACTIONS>
          <COMMENT ref="PR82L"/>
        </ACTIONS>
      </RULE>
    </GENE>
  </MUTATION_COMMENTS>
  
  <RESULT_COMMENTS>
	<RESULT_COMMENT_RULE>
		<DRUG_LEVEL_CONDITIONS>
			<DRUG_LEVEL_CONDITION>
				<DRUG_NAME>LPV/r</DRUG_NAME>
				<LTE>4</LTE>
			</DRUG_LEVEL_CONDITION>
		</DRUG_LEVEL_CONDITIONS>
		<LEVEL_ACTION>
			
		</LEVEL_ACTION>
	</RESULT_COMMENT_RULE>
</RESULT_COMMENTS>

</ALGORITHM>
