=== FrontierScience/asi_interpreter/test/files/regression_testing/dtd_files/ASI2.1.dtd
<!-- 
This DTD is being put together to indicate the format the various
drug resistance algorithms should use.

version 2.1  added ALGDATE
by tliu
-->


<!ELEMENT ALGORITHM (ALGNAME, ALGVERSION?, ALGDATE?, DEFINITIONS, DRUG*, MUTATION_COMMENTS?)>

<!-- *************************************************************** -->
<!ELEMENT ALGNAME (#PCDATA)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT ALGVERSION (#PCDATA)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT ALGDATE (#PCDATA)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT DEFINITIONS (GENE_DEFINITION*, LEVEL_DEFINITION*, DRUGCLASS*, GLOBALRANGE?,
                       COMMENT_DEFINITIONS?)>
<!ELEMENT GENE_DEFINITION (NAME, DRUGCLASSLIST?)>
<!ELEMENT DRUGCLASSLIST (#PCDATA)>                    
<!ELEMENT LEVEL_DEFINITION (ORDER, ORIGINAL, SIR)>
<!ELEMENT ORDER (#PCDATA)>
<!ELEMENT ORIGINAL (#PCDATA)>
<!ELEMENT SIR (#PCDATA)>
<!ELEMENT DRUGCLASS (NAME, DRUGLIST)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT DRUGLIST (#PCDATA)>
<!ELEMENT GLOBALRANGE (#PCDATA)>
<!ELEMENT COMMENT_DEFINITIONS (COMMENT_STRING+)>
<!ELEMENT COMMENT_STRING (TEXT, SORT_TAG?)>
<!ATTLIST COMMENT_STRING   id ID #REQUIRED>     
<!-- the html version of the HIVdb program expects the COMMENT_STRING id to be <geneName>_<mutation>_<commentType>
     the commentType is used for grouping the comments (uppercased) and should match the name of the appropriate MutationClassification element in the virus definition -->
<!ELEMENT TEXT (#PCDATA)>
<!ELEMENT SORT_TAG (#PCDATA)>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT DRUG (NAME, FULLNAME?, RULE*)>
<!ELEMENT FULLNAME (#PCDATA)>
<!ELEMENT RULE (CONDITION, ACTIONS)>
<!ELEMENT CONDITION (#PCDATA)>
<!ELEMENT ACTIONS (LEVEL?, SCORERANGE?, COMMENT?)>
<!ELEMENT LEVEL (#PCDATA)>
<!ELEMENT SCORERANGE (#PCDATA | USE_GLOBALRANGE)*>
<!ELEMENT USE_GLOBALRANGE EMPTY>
<!ELEMENT COMMENT EMPTY>
<!ATTLIST COMMENT   ref IDREF #REQUIRED>
<!-- *************************************************************** -->

<!-- *************************************************************** -->
<!ELEMENT MUTATION_COMMENTS (GENE*)>
<!ELEMENT GENE (NAME, RULE+)>
<!-- *************************************************************** -->

=== FrontierScience/asi_interpreter/test/files/resistance_xml/HIVDB_8.2_withInvalidTag.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE ALGORITHM SYSTEM "http://sierra2.stanford.edu/sierra/ASI2.1.dtd">
<ALGORITHM>
  <ALGNAME>HIVDB</ALGNAME>
  <ALGVERSION>8.2</ALGVERSION>
  <ALGDATE>2016-12-09</ALGDATE>
  <DEFINITIONS>
    <GENE_DEFINITION>
      <NAME>PR</NAME>
      <DRUGCLASSLIST>PI</DRUGCLASSLIST>
    </GENE_DEFINITION>
    <GENE_DEFINITION>
      <NAME>RT</NAME>
      <DRUGCLASSLIST>NRTI,NNRTI</DRUGCLASSLIST>
    </GENE_DEFINITION>
    <GENE_DEFINITION>
      <NAME>IN</NAME>
      <DRUGCLASSLIST>INSTI</DRUGCLASSLIST>
    </GENE_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>1</ORDER>
	<ATAG>extra</ATAG>
      <ORIGINAL>Susceptible</ORIGINAL>
      <SIR>S</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>2</ORDER>
      <ORIGINAL>Potential Low-Level Resistance</ORIGINAL>
      <SIR>S</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>3</ORDER>
      <ORIGINAL>Low-Level Resistance</ORIGINAL>
      <SIR>I</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>4</ORDER>
      <ORIGINAL>Intermediate Resistance</ORIGINAL>
      <SIR>I</SIR>
    </LEVEL_DEFINITION>
    <LEVEL_DEFINITION>
      <ORDER>5</ORDER>
      <ORIGINAL>High-Level Resistance</ORIGINAL>
      <SIR>R</SIR>
    </LEVEL_DEFINITION>
    <DRUGCLASS>
      <NAME>NRTI</NAME>
      <DRUGLIST>ABC,AZT,D4T,DDI,FTC,3TC,TDF</DRUGLIST>
    </DRUGCLASS>
    <DRUGCLASS>
      <NAME>NNRTI</NAME>
      <DRUGLIST>EFV,ETR,NVP,RPV</DRUGLIST>
    </DRUGCLASS>
    <DRUGCLASS>
      <NAME>PI</NAME>
      <DRUGLIST>ATV/r,DRV/r,FPV/r,IDV/r,LPV/r,NFV,SQV/r,TPV/r</DRUGLIST>
    </DRUGCLASS>
    <DRUGCLASS>
      <NAME>INSTI</NAME>
      <DRUGLIST>DTG,EVG,RAL</DRUGLIST>
    </DRUGCLASS>
    <GLOBALRANGE><![CDATA[(-INF TO 9 => 1,  10 TO 14 => 2,  15 TO 29 => 3,  30 TO 59 => 4,  60 TO INF => 5)]]></GLOBALRANGE>
    <COMMENT_DEFINITIONS>
      <COMMENT_STRING id="RT_POS40F_NRTI">
        <TEXT><![CDATA[E40F is a non-polymorphic accessory mutation selected by AZT and d4T.  It usually occurs in combination with M41L, L210W and T215Y.  In this context it is associated with reduced susceptibility to each of the NRTIs.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS41L_NRTI">
        <TEXT><![CDATA[M41L is a TAM that usually occurs with T215Y.  In combinaton, M41L plus T215Y confer intermediate / high-level resistance to AZT and d4T and contribute to reduced ddI, ABC and TDF susceptibility.  ]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS41I_Other">
        <TEXT><![CDATA[M41I is usually an artifact resulting from APOBEC3G-mediated hypermutation.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS44AD_NRTI">
        <TEXT><![CDATA[E44D is a relatively non-polymorphic accessory mutation and E44A is a nonpolymorphic accessory mutation. Each usually occurs with multiple TAMs.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS62V_NRTI">
        <TEXT><![CDATA[A62V is an accessory mutation that often occurs in combination with the multi-NRTI resistance mutations K65R or Q151M.  A62V is widespread in subtype A viruses in former Soviet Union countries but A62 is otherwise non-polymorphic.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS65R_NRTI">
        <TEXT><![CDATA[K65R causes intermediate/high-level resistance to TDF, ddI, ABC and d4T and low/intermediate resistance to 3TC and FTC.  K65R increases susceptibility to AZT.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS65N_NRTI">
        <TEXT><![CDATA[K65R causes intermediate/high-level resistance to TDF, ddI, ABC and d4T and low/intermediate resistance to 3TC and FTC.  K65R increases susceptibility to AZT.  K65N is a rare mutation with similar but less pronounced effects on NRTI susceptibility than K65R. ]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS65E_NRTI">
        <TEXT><![CDATA[K65R causes intermediate/high-level resistance to TDF, ddI, ABC and d4T and low/intermediate resistance to 3TC and FTC.  K65R increases susceptibility to AZT.  K65E is an extremely rare NRTI-selected mutation with markedly reduced replication fitness.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS65ACDFGHILMPQSTVWYid_NRTI">
        <TEXT><![CDATA[K65R causes intermediate/high-level resistance to TDF, ddI, ABC and d4T and low/intermediate resistance to 3TC and FTC.  K65R increases susceptibility to AZT. $listMutsIn{65(NOT NRE)} is a highly unusual mutation at this position.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS67N_NRTI">
        <TEXT><![CDATA[D67N is a non-polymorphic TAM associated with low-level resistance to AZT and d4T.  When present with other TAMs, it contributes reduced susceptibility to ABC, ddI, and TDF.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS67GESTH_NRTI">
        <TEXT><![CDATA[D67N is a non-polymorphic TAM associated with low-level resistance to AZT and d4T.  When present with other TAMs, it contributes reduced susceptibility to ABC, ddI, and TDF.  D67G/E/S/T/H are non-polymorphic NRTI-selected mutations that also generally occur in viruses with multiple TAMs.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS67d_NRTI">
        <TEXT><![CDATA[Amino acid deletions between codons 67 and 70 are rare and usually occur in combination with multiple TAMs, K65R, or the Q151M mutation complex. Deletions at position 67 are more often associated with multiple TAMs.  Deletions at positions 69 and 70 are more often associated with K65R or the Q151M mutation complex.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS67ACFIKLMPQRVWYi_NRTI">
        <TEXT><![CDATA[D67N is a non-polymorphic TAM associated with low-level resistance to AZT and d4T.  When present with other TAMs, it contributes reduced susceptibility to ABC, ddI, and TDF.  D67G/E/S/T/H are non-polymorphic NRTI-selected mutations that also generally occur in viruses with multiple TAMs.  $listMutsIn{67(NOT NGESTHd)} is a highly unusual mutation at this position.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS68d_NRTI">
        <TEXT><![CDATA[Amino acid deletions between codons 67 and 70 are rare and usually occur in combination with multiple TAMs, K65R, or the Q151M mutation complex. Deletions at position 67 are more often associated with multiple TAMs.  Deletions at positions 69 and 70 are more often associated with K65R or the Q151M mutation complex. Deletions at codon 68 are extremely rare and less well characterized.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS69d_NRTI">
        <TEXT><![CDATA[Amino acid deletions between codons 67 and 70 are rare and usually occur in combination with multiple TAMs, K65R, or the Q151M mutation complex. Deletions at position 67 are more often associated with multiple TAMs.  Deletions at positions 69 and 70 are more often associated with K65R or the Q151M mutation complex.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS69i_NRTI">
        <TEXT><![CDATA[Amino acid insertions between codons 67 and 70 are by convention assigned to codon 69. Together with TAMs, they are associated with high-level resistance to AZT, d4T, ddI, ABC and TDF and intermediate to 3TC and FTC.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS69D_NRTI">
        <TEXT><![CDATA[T69D is a non-polymorphic mutation that reduces susceptibility to ddI and possibly d4T.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS69G_NRTI">
        <TEXT><![CDATA[T69G is a rare non-polymorphic mutation that usually occurs in viruses with a deletion at codon 67 and multiple other NRTI-resistance mutations.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS69N_Other">
        <TEXT><![CDATA[T69N is a relatively non-polymorphic mutation weakly selected in patients receiving NRTIs. In combination with TAMs, it may contribute to reduced susceptibility to ddI, d4T, and AZT.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS69SAIE_Other">
        <TEXT><![CDATA[T69S/A/I/E are relatively polymorphic mutations weakly selected in patients receiving NRTIs.  Their effects on NRTI susceptibility have not been well studied.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS69CFHKLMPQRVWY_Other">
        <TEXT><![CDATA[T69D/N/G/S/A/I/E are NRTI-selected mutations.  $listMutsIn{69(NOT DNGSAIEid)} is a highly unusual mutation at this position.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS70R_NRTI">
        <TEXT><![CDATA[K70R causes intermediate resistance to AZT and possibly low-level resistance to d4T and TDF.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS70EG_NRTI">
        <TEXT><![CDATA[K70E/G cause low-level resistance to TDF, ABC, DDI and possibly 3TC and FTC.  K70E increases susceptibility to AZT.]]></TEXT>
        <SORT_TAG>1</SORT_TAG>
      </COMMENT_STRING>
      <COMMENT_STRING id="RT_POS70QNST_NRTI">
